// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_rpc.proto

package se.mouaz.jdistdb.protocol.pb;

public interface AppendEntriesArgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:se.mouaz.jdistdb.protocol.AppendEntriesArgs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 term = 1;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <code>string leader_id = 2;</code>
   * @return The leaderId.
   */
  java.lang.String getLeaderId();
  /**
   * <code>string leader_id = 2;</code>
   * @return The bytes for leaderId.
   */
  com.google.protobuf.ByteString
      getLeaderIdBytes();

  /**
   * <code>int64 prev_log_index = 3;</code>
   * @return The prevLogIndex.
   */
  long getPrevLogIndex();

  /**
   * <code>int64 prev_log_term = 4;</code>
   * @return The prevLogTerm.
   */
  long getPrevLogTerm();

  /**
   * <code>bytes entries = 5;</code>
   * @return The entries.
   */
  com.google.protobuf.ByteString getEntries();

  /**
   * <code>int64 leader_commit = 6;</code>
   * @return The leaderCommit.
   */
  long getLeaderCommit();
}
