// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_rpc.proto

package se.mouaz.jdistdb.protocol.pb;

public final class RaftRpc {
  private RaftRpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_se_mouaz_jdistdb_protocol_RequestVoteArgs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_se_mouaz_jdistdb_protocol_RequestVoteArgs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_se_mouaz_jdistdb_protocol_RequestVoteReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_se_mouaz_jdistdb_protocol_RequestVoteReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_se_mouaz_jdistdb_protocol_AppendEntriesArgs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_se_mouaz_jdistdb_protocol_AppendEntriesArgs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_se_mouaz_jdistdb_protocol_AppendEntriesReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_se_mouaz_jdistdb_protocol_AppendEntriesReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016raft_rpc.proto\022\031se.mouaz.jdistdb.proto" +
      "col\"d\n\017RequestVoteArgs\022\024\n\014candidate_id\030\001" +
      " \001(\t\022\014\n\004term\030\002 \001(\003\022\026\n\016last_log_index\030\003 \001" +
      "(\003\022\025\n\rlast_log_term\030\004 \001(\003\"F\n\020RequestVote" +
      "Reply\022\014\n\004term\030\001 \001(\003\022\024\n\014vote_granted\030\002 \001(" +
      "\010\022\016\n\006reason\030\003 \001(\t\"\213\001\n\021AppendEntriesArgs\022" +
      "\014\n\004term\030\001 \001(\003\022\021\n\tleader_id\030\002 \001(\t\022\026\n\016prev" +
      "_log_index\030\003 \001(\003\022\025\n\rprev_log_term\030\004 \001(\003\022" +
      "\017\n\007entries\030\005 \001(\014\022\025\n\rleader_commit\030\006 \001(\003\"" +
      "X\n\022AppendEntriesReply\022\014\n\004term\030\001 \001(\003\022\017\n\007s" +
      "uccess\030\002 \001(\010\022\023\n\013match_index\030\003 \001(\003\022\016\n\006rea" +
      "son\030\004 \001(\t2\346\001\n\016RaftRpcService\022f\n\013RequestV" +
      "ote\022*.se.mouaz.jdistdb.protocol.RequestV" +
      "oteArgs\032+.se.mouaz.jdistdb.protocol.Requ" +
      "estVoteReply\022l\n\rAppendEntries\022,.se.mouaz" +
      ".jdistdb.protocol.AppendEntriesArgs\032-.se" +
      ".mouaz.jdistdb.protocol.AppendEntriesRep" +
      "lyB \n\034se.mouaz.jdistdb.protocol.pbP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_se_mouaz_jdistdb_protocol_RequestVoteArgs_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_se_mouaz_jdistdb_protocol_RequestVoteArgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_se_mouaz_jdistdb_protocol_RequestVoteArgs_descriptor,
        new java.lang.String[] { "CandidateId", "Term", "LastLogIndex", "LastLogTerm", });
    internal_static_se_mouaz_jdistdb_protocol_RequestVoteReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_se_mouaz_jdistdb_protocol_RequestVoteReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_se_mouaz_jdistdb_protocol_RequestVoteReply_descriptor,
        new java.lang.String[] { "Term", "VoteGranted", "Reason", });
    internal_static_se_mouaz_jdistdb_protocol_AppendEntriesArgs_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_se_mouaz_jdistdb_protocol_AppendEntriesArgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_se_mouaz_jdistdb_protocol_AppendEntriesArgs_descriptor,
        new java.lang.String[] { "Term", "LeaderId", "PrevLogIndex", "PrevLogTerm", "Entries", "LeaderCommit", });
    internal_static_se_mouaz_jdistdb_protocol_AppendEntriesReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_se_mouaz_jdistdb_protocol_AppendEntriesReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_se_mouaz_jdistdb_protocol_AppendEntriesReply_descriptor,
        new java.lang.String[] { "Term", "Success", "MatchIndex", "Reason", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
