// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_rpc.proto

package se.mouaz.jdistdb.protocol.pb;

public interface RequestVoteArgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:se.mouaz.jdistdb.protocol.RequestVoteArgs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string candidate_id = 1;</code>
   * @return The candidateId.
   */
  java.lang.String getCandidateId();
  /**
   * <code>string candidate_id = 1;</code>
   * @return The bytes for candidateId.
   */
  com.google.protobuf.ByteString
      getCandidateIdBytes();

  /**
   * <code>int64 term = 2;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <code>int64 last_log_index = 3;</code>
   * @return The lastLogIndex.
   */
  long getLastLogIndex();

  /**
   * <code>int64 last_log_term = 4;</code>
   * @return The lastLogTerm.
   */
  long getLastLogTerm();
}
