// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_rpc.proto

package se.mouaz.jdistdb.protocol.pb;

public interface RequestVoteReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:se.mouaz.jdistdb.protocol.RequestVoteReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 term = 1;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <code>bool vote_granted = 2;</code>
   * @return The voteGranted.
   */
  boolean getVoteGranted();

  /**
   * <code>string reason = 3;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 3;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
