// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_rpc.proto

package se.mouaz.aegisdb.protocol.pb;

public interface AppendEntriesReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:se.mouaz.aegisdb.protocol.AppendEntriesReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 term = 1;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>int64 match_index = 3;</code>
   * @return The matchIndex.
   */
  long getMatchIndex();

  /**
   * <code>string reason = 4;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 4;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
