// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_rpc.proto

package se.mouaz.aegisdb.protocol.pb;

public interface InstallSnapshotArgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:se.mouaz.aegisdb.protocol.InstallSnapshotArgs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 term = 1;</code>
   * @return The term.
   */
  long getTerm();

  /**
   * <code>string leader_id = 2;</code>
   * @return The leaderId.
   */
  java.lang.String getLeaderId();
  /**
   * <code>string leader_id = 2;</code>
   * @return The bytes for leaderId.
   */
  com.google.protobuf.ByteString
      getLeaderIdBytes();

  /**
   * <code>int64 last_included_index = 3;</code>
   * @return The lastIncludedIndex.
   */
  long getLastIncludedIndex();

  /**
   * <code>int64 last_included_term = 4;</code>
   * @return The lastIncludedTerm.
   */
  long getLastIncludedTerm();

  /**
   * <code>int64 offset = 5;</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <code>bytes data = 6;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>bool done = 7;</code>
   * @return The done.
   */
  boolean getDone();
}
