// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_rpc.proto

package se.mouaz.aegisdb.protocol.pb;

/**
 * Protobuf type {@code se.mouaz.aegisdb.protocol.InstallSnapshotArgs}
 */
public final class InstallSnapshotArgs extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:se.mouaz.aegisdb.protocol.InstallSnapshotArgs)
    InstallSnapshotArgsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InstallSnapshotArgs.newBuilder() to construct.
  private InstallSnapshotArgs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InstallSnapshotArgs() {
    leaderId_ = "";
    data_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InstallSnapshotArgs();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return se.mouaz.aegisdb.protocol.pb.RaftRpc.internal_static_se_mouaz_aegisdb_protocol_InstallSnapshotArgs_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return se.mouaz.aegisdb.protocol.pb.RaftRpc.internal_static_se_mouaz_aegisdb_protocol_InstallSnapshotArgs_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs.class, se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs.Builder.class);
  }

  public static final int TERM_FIELD_NUMBER = 1;
  private long term_ = 0L;
  /**
   * <code>int64 term = 1;</code>
   * @return The term.
   */
  @java.lang.Override
  public long getTerm() {
    return term_;
  }

  public static final int LEADER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object leaderId_ = "";
  /**
   * <code>string leader_id = 2;</code>
   * @return The leaderId.
   */
  @java.lang.Override
  public java.lang.String getLeaderId() {
    java.lang.Object ref = leaderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      leaderId_ = s;
      return s;
    }
  }
  /**
   * <code>string leader_id = 2;</code>
   * @return The bytes for leaderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLeaderIdBytes() {
    java.lang.Object ref = leaderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      leaderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_INCLUDED_INDEX_FIELD_NUMBER = 3;
  private long lastIncludedIndex_ = 0L;
  /**
   * <code>int64 last_included_index = 3;</code>
   * @return The lastIncludedIndex.
   */
  @java.lang.Override
  public long getLastIncludedIndex() {
    return lastIncludedIndex_;
  }

  public static final int LAST_INCLUDED_TERM_FIELD_NUMBER = 4;
  private long lastIncludedTerm_ = 0L;
  /**
   * <code>int64 last_included_term = 4;</code>
   * @return The lastIncludedTerm.
   */
  @java.lang.Override
  public long getLastIncludedTerm() {
    return lastIncludedTerm_;
  }

  public static final int OFFSET_FIELD_NUMBER = 5;
  private long offset_ = 0L;
  /**
   * <code>int64 offset = 5;</code>
   * @return The offset.
   */
  @java.lang.Override
  public long getOffset() {
    return offset_;
  }

  public static final int DATA_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes data = 6;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int DONE_FIELD_NUMBER = 7;
  private boolean done_ = false;
  /**
   * <code>bool done = 7;</code>
   * @return The done.
   */
  @java.lang.Override
  public boolean getDone() {
    return done_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (term_ != 0L) {
      output.writeInt64(1, term_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, leaderId_);
    }
    if (lastIncludedIndex_ != 0L) {
      output.writeInt64(3, lastIncludedIndex_);
    }
    if (lastIncludedTerm_ != 0L) {
      output.writeInt64(4, lastIncludedTerm_);
    }
    if (offset_ != 0L) {
      output.writeInt64(5, offset_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(6, data_);
    }
    if (done_ != false) {
      output.writeBool(7, done_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (term_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, term_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(leaderId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, leaderId_);
    }
    if (lastIncludedIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, lastIncludedIndex_);
    }
    if (lastIncludedTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, lastIncludedTerm_);
    }
    if (offset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, offset_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, data_);
    }
    if (done_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, done_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs)) {
      return super.equals(obj);
    }
    se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs other = (se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs) obj;

    if (getTerm()
        != other.getTerm()) return false;
    if (!getLeaderId()
        .equals(other.getLeaderId())) return false;
    if (getLastIncludedIndex()
        != other.getLastIncludedIndex()) return false;
    if (getLastIncludedTerm()
        != other.getLastIncludedTerm()) return false;
    if (getOffset()
        != other.getOffset()) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (getDone()
        != other.getDone()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTerm());
    hash = (37 * hash) + LEADER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLeaderId().hashCode();
    hash = (37 * hash) + LAST_INCLUDED_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastIncludedIndex());
    hash = (37 * hash) + LAST_INCLUDED_TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastIncludedTerm());
    hash = (37 * hash) + OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOffset());
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + DONE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDone());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code se.mouaz.aegisdb.protocol.InstallSnapshotArgs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:se.mouaz.aegisdb.protocol.InstallSnapshotArgs)
      se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return se.mouaz.aegisdb.protocol.pb.RaftRpc.internal_static_se_mouaz_aegisdb_protocol_InstallSnapshotArgs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return se.mouaz.aegisdb.protocol.pb.RaftRpc.internal_static_se_mouaz_aegisdb_protocol_InstallSnapshotArgs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs.class, se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs.Builder.class);
    }

    // Construct using se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      term_ = 0L;
      leaderId_ = "";
      lastIncludedIndex_ = 0L;
      lastIncludedTerm_ = 0L;
      offset_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
      done_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return se.mouaz.aegisdb.protocol.pb.RaftRpc.internal_static_se_mouaz_aegisdb_protocol_InstallSnapshotArgs_descriptor;
    }

    @java.lang.Override
    public se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs getDefaultInstanceForType() {
      return se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs.getDefaultInstance();
    }

    @java.lang.Override
    public se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs build() {
      se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs buildPartial() {
      se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs result = new se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.term_ = term_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.leaderId_ = leaderId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.lastIncludedIndex_ = lastIncludedIndex_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.lastIncludedTerm_ = lastIncludedTerm_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.offset_ = offset_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.data_ = data_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.done_ = done_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs) {
        return mergeFrom((se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs other) {
      if (other == se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs.getDefaultInstance()) return this;
      if (other.getTerm() != 0L) {
        setTerm(other.getTerm());
      }
      if (!other.getLeaderId().isEmpty()) {
        leaderId_ = other.leaderId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getLastIncludedIndex() != 0L) {
        setLastIncludedIndex(other.getLastIncludedIndex());
      }
      if (other.getLastIncludedTerm() != 0L) {
        setLastIncludedTerm(other.getLastIncludedTerm());
      }
      if (other.getOffset() != 0L) {
        setOffset(other.getOffset());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      if (other.getDone() != false) {
        setDone(other.getDone());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              term_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              leaderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              lastIncludedIndex_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              lastIncludedTerm_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              offset_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              data_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              done_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long term_ ;
    /**
     * <code>int64 term = 1;</code>
     * @return The term.
     */
    @java.lang.Override
    public long getTerm() {
      return term_;
    }
    /**
     * <code>int64 term = 1;</code>
     * @param value The term to set.
     * @return This builder for chaining.
     */
    public Builder setTerm(long value) {
      
      term_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 term = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTerm() {
      bitField0_ = (bitField0_ & ~0x00000001);
      term_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object leaderId_ = "";
    /**
     * <code>string leader_id = 2;</code>
     * @return The leaderId.
     */
    public java.lang.String getLeaderId() {
      java.lang.Object ref = leaderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string leader_id = 2;</code>
     * @return The bytes for leaderId.
     */
    public com.google.protobuf.ByteString
        getLeaderIdBytes() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string leader_id = 2;</code>
     * @param value The leaderId to set.
     * @return This builder for chaining.
     */
    public Builder setLeaderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      leaderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string leader_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeaderId() {
      leaderId_ = getDefaultInstance().getLeaderId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string leader_id = 2;</code>
     * @param value The bytes for leaderId to set.
     * @return This builder for chaining.
     */
    public Builder setLeaderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      leaderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long lastIncludedIndex_ ;
    /**
     * <code>int64 last_included_index = 3;</code>
     * @return The lastIncludedIndex.
     */
    @java.lang.Override
    public long getLastIncludedIndex() {
      return lastIncludedIndex_;
    }
    /**
     * <code>int64 last_included_index = 3;</code>
     * @param value The lastIncludedIndex to set.
     * @return This builder for chaining.
     */
    public Builder setLastIncludedIndex(long value) {
      
      lastIncludedIndex_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_included_index = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastIncludedIndex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      lastIncludedIndex_ = 0L;
      onChanged();
      return this;
    }

    private long lastIncludedTerm_ ;
    /**
     * <code>int64 last_included_term = 4;</code>
     * @return The lastIncludedTerm.
     */
    @java.lang.Override
    public long getLastIncludedTerm() {
      return lastIncludedTerm_;
    }
    /**
     * <code>int64 last_included_term = 4;</code>
     * @param value The lastIncludedTerm to set.
     * @return This builder for chaining.
     */
    public Builder setLastIncludedTerm(long value) {
      
      lastIncludedTerm_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_included_term = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastIncludedTerm() {
      bitField0_ = (bitField0_ & ~0x00000008);
      lastIncludedTerm_ = 0L;
      onChanged();
      return this;
    }

    private long offset_ ;
    /**
     * <code>int64 offset = 5;</code>
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }
    /**
     * <code>int64 offset = 5;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(long value) {
      
      offset_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 offset = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      bitField0_ = (bitField0_ & ~0x00000010);
      offset_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 6;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 6;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      data_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bytes data = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000020);
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private boolean done_ ;
    /**
     * <code>bool done = 7;</code>
     * @return The done.
     */
    @java.lang.Override
    public boolean getDone() {
      return done_;
    }
    /**
     * <code>bool done = 7;</code>
     * @param value The done to set.
     * @return This builder for chaining.
     */
    public Builder setDone(boolean value) {
      
      done_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool done = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDone() {
      bitField0_ = (bitField0_ & ~0x00000040);
      done_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:se.mouaz.aegisdb.protocol.InstallSnapshotArgs)
  }

  // @@protoc_insertion_point(class_scope:se.mouaz.aegisdb.protocol.InstallSnapshotArgs)
  private static final se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs();
  }

  public static se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InstallSnapshotArgs>
      PARSER = new com.google.protobuf.AbstractParser<InstallSnapshotArgs>() {
    @java.lang.Override
    public InstallSnapshotArgs parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InstallSnapshotArgs> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InstallSnapshotArgs> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public se.mouaz.aegisdb.protocol.pb.InstallSnapshotArgs getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

