// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft_rpc.proto

package se.mouaz.aegisdb.protocol.pb;

/**
 * Protobuf type {@code se.mouaz.aegisdb.protocol.RequestVoteArgs}
 */
public final class RequestVoteArgs extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:se.mouaz.aegisdb.protocol.RequestVoteArgs)
    RequestVoteArgsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestVoteArgs.newBuilder() to construct.
  private RequestVoteArgs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestVoteArgs() {
    candidateId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestVoteArgs();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return se.mouaz.aegisdb.protocol.pb.RaftRpc.internal_static_se_mouaz_aegisdb_protocol_RequestVoteArgs_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return se.mouaz.aegisdb.protocol.pb.RaftRpc.internal_static_se_mouaz_aegisdb_protocol_RequestVoteArgs_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            se.mouaz.aegisdb.protocol.pb.RequestVoteArgs.class, se.mouaz.aegisdb.protocol.pb.RequestVoteArgs.Builder.class);
  }

  public static final int CANDIDATE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object candidateId_ = "";
  /**
   * <code>string candidate_id = 1;</code>
   * @return The candidateId.
   */
  @java.lang.Override
  public java.lang.String getCandidateId() {
    java.lang.Object ref = candidateId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      candidateId_ = s;
      return s;
    }
  }
  /**
   * <code>string candidate_id = 1;</code>
   * @return The bytes for candidateId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCandidateIdBytes() {
    java.lang.Object ref = candidateId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      candidateId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TERM_FIELD_NUMBER = 2;
  private long term_ = 0L;
  /**
   * <code>int64 term = 2;</code>
   * @return The term.
   */
  @java.lang.Override
  public long getTerm() {
    return term_;
  }

  public static final int LAST_LOG_INDEX_FIELD_NUMBER = 3;
  private long lastLogIndex_ = 0L;
  /**
   * <code>int64 last_log_index = 3;</code>
   * @return The lastLogIndex.
   */
  @java.lang.Override
  public long getLastLogIndex() {
    return lastLogIndex_;
  }

  public static final int LAST_LOG_TERM_FIELD_NUMBER = 4;
  private long lastLogTerm_ = 0L;
  /**
   * <code>int64 last_log_term = 4;</code>
   * @return The lastLogTerm.
   */
  @java.lang.Override
  public long getLastLogTerm() {
    return lastLogTerm_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(candidateId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, candidateId_);
    }
    if (term_ != 0L) {
      output.writeInt64(2, term_);
    }
    if (lastLogIndex_ != 0L) {
      output.writeInt64(3, lastLogIndex_);
    }
    if (lastLogTerm_ != 0L) {
      output.writeInt64(4, lastLogTerm_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(candidateId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, candidateId_);
    }
    if (term_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, term_);
    }
    if (lastLogIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, lastLogIndex_);
    }
    if (lastLogTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, lastLogTerm_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof se.mouaz.aegisdb.protocol.pb.RequestVoteArgs)) {
      return super.equals(obj);
    }
    se.mouaz.aegisdb.protocol.pb.RequestVoteArgs other = (se.mouaz.aegisdb.protocol.pb.RequestVoteArgs) obj;

    if (!getCandidateId()
        .equals(other.getCandidateId())) return false;
    if (getTerm()
        != other.getTerm()) return false;
    if (getLastLogIndex()
        != other.getLastLogIndex()) return false;
    if (getLastLogTerm()
        != other.getLastLogTerm()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CANDIDATE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCandidateId().hashCode();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTerm());
    hash = (37 * hash) + LAST_LOG_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastLogIndex());
    hash = (37 * hash) + LAST_LOG_TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastLogTerm());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(se.mouaz.aegisdb.protocol.pb.RequestVoteArgs prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code se.mouaz.aegisdb.protocol.RequestVoteArgs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:se.mouaz.aegisdb.protocol.RequestVoteArgs)
      se.mouaz.aegisdb.protocol.pb.RequestVoteArgsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return se.mouaz.aegisdb.protocol.pb.RaftRpc.internal_static_se_mouaz_aegisdb_protocol_RequestVoteArgs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return se.mouaz.aegisdb.protocol.pb.RaftRpc.internal_static_se_mouaz_aegisdb_protocol_RequestVoteArgs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              se.mouaz.aegisdb.protocol.pb.RequestVoteArgs.class, se.mouaz.aegisdb.protocol.pb.RequestVoteArgs.Builder.class);
    }

    // Construct using se.mouaz.aegisdb.protocol.pb.RequestVoteArgs.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      candidateId_ = "";
      term_ = 0L;
      lastLogIndex_ = 0L;
      lastLogTerm_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return se.mouaz.aegisdb.protocol.pb.RaftRpc.internal_static_se_mouaz_aegisdb_protocol_RequestVoteArgs_descriptor;
    }

    @java.lang.Override
    public se.mouaz.aegisdb.protocol.pb.RequestVoteArgs getDefaultInstanceForType() {
      return se.mouaz.aegisdb.protocol.pb.RequestVoteArgs.getDefaultInstance();
    }

    @java.lang.Override
    public se.mouaz.aegisdb.protocol.pb.RequestVoteArgs build() {
      se.mouaz.aegisdb.protocol.pb.RequestVoteArgs result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public se.mouaz.aegisdb.protocol.pb.RequestVoteArgs buildPartial() {
      se.mouaz.aegisdb.protocol.pb.RequestVoteArgs result = new se.mouaz.aegisdb.protocol.pb.RequestVoteArgs(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(se.mouaz.aegisdb.protocol.pb.RequestVoteArgs result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.candidateId_ = candidateId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.term_ = term_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.lastLogIndex_ = lastLogIndex_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.lastLogTerm_ = lastLogTerm_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof se.mouaz.aegisdb.protocol.pb.RequestVoteArgs) {
        return mergeFrom((se.mouaz.aegisdb.protocol.pb.RequestVoteArgs)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(se.mouaz.aegisdb.protocol.pb.RequestVoteArgs other) {
      if (other == se.mouaz.aegisdb.protocol.pb.RequestVoteArgs.getDefaultInstance()) return this;
      if (!other.getCandidateId().isEmpty()) {
        candidateId_ = other.candidateId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTerm() != 0L) {
        setTerm(other.getTerm());
      }
      if (other.getLastLogIndex() != 0L) {
        setLastLogIndex(other.getLastLogIndex());
      }
      if (other.getLastLogTerm() != 0L) {
        setLastLogTerm(other.getLastLogTerm());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              candidateId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              term_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              lastLogIndex_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              lastLogTerm_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object candidateId_ = "";
    /**
     * <code>string candidate_id = 1;</code>
     * @return The candidateId.
     */
    public java.lang.String getCandidateId() {
      java.lang.Object ref = candidateId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidateId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string candidate_id = 1;</code>
     * @return The bytes for candidateId.
     */
    public com.google.protobuf.ByteString
        getCandidateIdBytes() {
      java.lang.Object ref = candidateId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string candidate_id = 1;</code>
     * @param value The candidateId to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      candidateId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string candidate_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidateId() {
      candidateId_ = getDefaultInstance().getCandidateId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string candidate_id = 1;</code>
     * @param value The bytes for candidateId to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      candidateId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long term_ ;
    /**
     * <code>int64 term = 2;</code>
     * @return The term.
     */
    @java.lang.Override
    public long getTerm() {
      return term_;
    }
    /**
     * <code>int64 term = 2;</code>
     * @param value The term to set.
     * @return This builder for chaining.
     */
    public Builder setTerm(long value) {
      
      term_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 term = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTerm() {
      bitField0_ = (bitField0_ & ~0x00000002);
      term_ = 0L;
      onChanged();
      return this;
    }

    private long lastLogIndex_ ;
    /**
     * <code>int64 last_log_index = 3;</code>
     * @return The lastLogIndex.
     */
    @java.lang.Override
    public long getLastLogIndex() {
      return lastLogIndex_;
    }
    /**
     * <code>int64 last_log_index = 3;</code>
     * @param value The lastLogIndex to set.
     * @return This builder for chaining.
     */
    public Builder setLastLogIndex(long value) {
      
      lastLogIndex_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_log_index = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastLogIndex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      lastLogIndex_ = 0L;
      onChanged();
      return this;
    }

    private long lastLogTerm_ ;
    /**
     * <code>int64 last_log_term = 4;</code>
     * @return The lastLogTerm.
     */
    @java.lang.Override
    public long getLastLogTerm() {
      return lastLogTerm_;
    }
    /**
     * <code>int64 last_log_term = 4;</code>
     * @param value The lastLogTerm to set.
     * @return This builder for chaining.
     */
    public Builder setLastLogTerm(long value) {
      
      lastLogTerm_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_log_term = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastLogTerm() {
      bitField0_ = (bitField0_ & ~0x00000008);
      lastLogTerm_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:se.mouaz.aegisdb.protocol.RequestVoteArgs)
  }

  // @@protoc_insertion_point(class_scope:se.mouaz.aegisdb.protocol.RequestVoteArgs)
  private static final se.mouaz.aegisdb.protocol.pb.RequestVoteArgs DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new se.mouaz.aegisdb.protocol.pb.RequestVoteArgs();
  }

  public static se.mouaz.aegisdb.protocol.pb.RequestVoteArgs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestVoteArgs>
      PARSER = new com.google.protobuf.AbstractParser<RequestVoteArgs>() {
    @java.lang.Override
    public RequestVoteArgs parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RequestVoteArgs> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestVoteArgs> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public se.mouaz.aegisdb.protocol.pb.RequestVoteArgs getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

