package se.mouaz.aegisdb.common;

public enum ErrorCode {
    TIMEOUT,
    NODE_NOT_FOUND,
    NODE_STOPPED,
    NETWORK_ERROR,
    INVALID_CONFIGURATION,
    ILLEGAL_STATE,
    INTERNAL_ERROR,
    NOT_LEADER,
    STALE_EPOCH,
    SPLITTING_RANGE,
    SPLIT_ABORTED,
    SPLIT_PRECONDITION_FAILED,
    SPLIT_TRANSACTION_CONFLICT,
    SHARD_NOT_ACTIVATED
}
